vpc_name                = "tf_test_ecs_instace"
subnet_name             = "tf_test_ecs_instace"
security_group_name     = "tf_test_ecs_instace"
instance_name           = "tf_test_ecs_instace"
volume_name             = "tf_test_volume"
